In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/trab1/cursos-prouni.csv - cursos-prouni-2018-tratados.csv.csv',
                    )

In [5]:
df.head()

grau     turno  mensalidade  bolsa_integral_cotas  \
0  Bacharelado  Integral      9715.61                   2.0   
1  Bacharelado  Integral      9674.34                   4.0   
2  Bacharelado  Integral      9023.07                   4.0   
3  Bacharelado  Integral      8508.54                   2.0   
4  Bacharelado  Integral      8281.38                   3.0   

   bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
0                   5.0                  6.0                 10.0   
1                   1.0                  5.0                  2.0   
2                   4.0                  5.0                  5.0   
3                   1.0                  7.0                  2.0   
4                   1.0                  6.0                  2.0   

          curso_id curso_busca cidade_busca uf_busca  \
0    1002328574024    Medicina    Sao Paulo       SP   
1   65899611932754    Medicina   Rio Branco       AC   
2   65921511844324    Medicina    Itaperuna       RJ   
3  104123711716094    Medicina        Belem       PA   
4  105887911921884    Medicina   Imperatriz       MA   

                             universidade_nome      nome  nota_integral_ampla  \
0    Universidade Cidade de São Paulo - UNICID  Medicina               739.62   
1          Faculdade Barão do Rio Branco - FAB  Medicina               758.32   
2             Faculdade Redentor - FACREDENTOR  Medicina               741.06   
3  Faculdade Metropolitana da Amazônia - FAMAZ  Medicina               741.36   
4  Universidade do Ceuma - Uniceuma - UNICEUMA  Medicina               756.46   

   nota_integral_cotas  nota_parcial_ampla  nota_parcial_cotas  
0               738.08              738.96              718.64  
1               723.94              734.92              711.26  
2               729.02              730.98              722.82  
3               739.90              760.80              715.10  
4               737.88              747.14              717.60

In [6]:
list_drop_columns = ['grau',
                     'turno',
                     'curso_busca',
                     'curso_id',
                     'bolsa_parcial_ampla',
                     'bolsa_parcial_cotas',
                     'bolsa_integral_ampla',
                     'bolsa_integral_cotas',
                     'mensalidade',
                     'cidade_busca',
                     'uf_busca',
                    'universidade_nome',
                     ]

df_aux = df.drop(columns=list_drop_columns)
df_aux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2203 entries, 0 to 2202
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   nome                 2203 non-null   object 
 1   nota_integral_ampla  2203 non-null   float64
 2   nota_integral_cotas  2203 non-null   float64
 3   nota_parcial_ampla   2203 non-null   float64
 4   nota_parcial_cotas   2203 non-null   float64
dtypes: float64(4), object(1)
memory usage: 86.2+ KB


In [7]:
df_aux.head()

nome  nota_integral_ampla  nota_integral_cotas  nota_parcial_ampla  \
0  Medicina               739.62               738.08              738.96   
1  Medicina               758.32               723.94              734.92   
2  Medicina               741.06               729.02              730.98   
3  Medicina               741.36               739.90              760.80   
4  Medicina               756.46               737.88              747.14   

   nota_parcial_cotas  
0              718.64  
1              711.26  
2              722.82  
3              715.10  
4              717.60

In [8]:
# Label Encoder

from sklearn.preprocessing import LabelEncoder

In [9]:
df_aux.head()

nome  nota_integral_ampla  nota_integral_cotas  nota_parcial_ampla  \
0  Medicina               739.62               738.08              738.96   
1  Medicina               758.32               723.94              734.92   
2  Medicina               741.06               729.02              730.98   
3  Medicina               741.36               739.90              760.80   
4  Medicina               756.46               737.88              747.14   

   nota_parcial_cotas  
0              718.64  
1              711.26  
2              722.82  
3              715.10  
4              717.60

In [10]:
df_pca = df_aux.iloc[:,:].values
df_pca

array([['Medicina', 739.62, 738.08, 738.96, 718.64],
       ['Medicina', 758.32, 723.94, 734.92, 711.26],
       ['Medicina', 741.06, 729.02, 730.98, 722.82],
       ...,
       ['Pedagogia', 497.78, 506.78, 508.48, 451.78],
       ['Gestão da Qualidade', 456.66, 450.0, 450.0, 450.0],
       ['Marketing', 533.34, 450.0, 450.0, 450.0]], dtype=object)

In [11]:
le = LabelEncoder()
df_pca = le.fit_transform(df_pca[:,1])
df_pca

array([1894, 1904, 1895, ...,   47,    5,  166])

In [12]:
list(le.classes_)

[450.0,
 451.36,
 453.22,
 454.42,
 456.64,
 456.66,
 459.58,
 459.7,
 463.6,
 464.58,
 466.56,
 467.26,
 467.36,
 469.12,
 469.36,
 469.42,
 469.78,
 469.84,
 471.08,
 473.16,
 475.3,
 478.1,
 478.38,
 479.56,
 481.4,
 481.44,
 485.22,
 486.18,
 486.22,
 486.52,
 487.5,
 487.78,
 488.84,
 490.12,
 490.56,
 490.78,
 491.18,
 491.46,
 491.72,
 492.44,
 493.08,
 493.7,
 493.84,
 493.88,
 494.82,
 496.68,
 497.0,
 497.78,
 497.82,
 498.36,
 498.46,
 498.62,
 498.66,
 498.94,
 501.52,
 502.78,
 503.22,
 503.52,
 503.64,
 504.16,
 504.7,
 505.58,
 505.68,
 505.7,
 505.78,
 506.08,
 506.22,
 507.14,
 508.16,
 509.22,
 509.26,
 509.78,
 510.0,
 510.32,
 510.86,
 510.92,
 511.02,
 511.16,
 511.26,
 511.28,
 511.36,
 511.66,
 511.7,
 511.82,
 511.86,
 511.9,
 512.58,
 512.6,
 513.32,
 514.08,
 514.16,
 514.3,
 514.48,
 515.6,
 516.2,
 516.26,
 516.82,
 516.84,
 517.08,
 517.2,
 517.6,
 518.16,
 518.46,
 518.48,
 518.7,
 518.8,
 518.88,
 518.94,
 519.0,
 519.04,
 519.1,
 519.34,
 519.66,
 519.88

In [13]:
df_aux['nome'] = df_pca
df_aux.head()

nome  nota_integral_ampla  nota_integral_cotas  nota_parcial_ampla  \
0  1894               739.62               738.08              738.96   
1  1904               758.32               723.94              734.92   
2  1895               741.06               729.02              730.98   
3  1896               741.36               739.90              760.80   
4  1902               756.46               737.88              747.14   

   nota_parcial_cotas  
0              718.64  
1              711.26  
2              722.82  
3              715.10  
4              717.60

In [14]:
inverted = le.inverse_transform(df_pca)
print(inverted)

[739.62 758.32 741.06 ... 497.78 456.66 533.34]


In [15]:
from sklearn.decomposition import PCA

In [16]:
pca = PCA(n_components=2)

In [17]:
pca_transform = pca.fit_transform(df_aux)

In [18]:
pca_transform.shape

(2203, 2)

In [19]:
# Componentes principais
pca_transform

array([[1001.10560278,  190.70823023],
       [1010.63293457,  177.36812286],
       [1001.15069189,  184.29898265],
       ...,
       [-899.99995502,   20.37190724],
       [-954.63806765,  -38.87483028],
       [-788.788348  ,  -56.61577107]])

In [20]:
# razão das variáveis explicativas
pca.explained_variance_ratio_

array([0.98493563, 0.00911346])

In [21]:
# Soma das variáveis explicativas
pca.explained_variance_ratio_.sum()

0.9940490929472576

In [22]:
import plotly.express as px

In [23]:
labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}

fig = px.scatter_matrix(
    pca_transform,
    labels=labels,
    dimensions=range(2),
    color=df_aux["nome"]
)
fig.update_traces(diagonal_visible=False)
fig.show()